/*
 * This source file was generated by the Gradle 'init' task
 */
package server;

import java.io.File;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import io.javalin.Javalin;
import niwer.lumen.Console;
import niwer.lumen.LumenEngine;
import niwer.lumen.container.Container;
import niwer.queryon.DataBase;
import niwer.queryon.QueryonException;
import server.endpoints.IEndpoint;
import server.endpoints.auth.PostAuthSignIn;
import server.endpoints.auth.PostAuthSignUp;
import server.endpoints.orders.DeleteOrder;
import server.endpoints.orders.GetOrderItems;
import server.endpoints.orders.GetOrders;
import server.endpoints.orders.PostOrders;
import server.endpoints.orders.PutOrderStatus;
import server.endpoints.pickupslots.DeletePickupSlot;
import server.endpoints.pickupslots.GetPickupSlots;
import server.endpoints.pickupslots.PostPickupSlots;
import server.endpoints.pickupslots.PutPickupSlotCapacity;
import server.endpoints.pickupslots.PutPickupSlotStatus;
import server.endpoints.products.DeleteProduct;
import server.endpoints.products.GetProducts;
import server.endpoints.products.PostProducts;
import server.endpoints.products.PutProductDetails;
import server.endpoints.products.PutProductStock;
import server.logging.CroissantFlowLogTypes;
import server.tables.TableAnalyticsMetric;
import server.tables.TableCustomerOrder;
import server.tables.TableOrderItem;
import server.tables.TablePickupSlot;
import server.tables.TableProduct;
import server.tables.TableUser;

/**
 * Main class of the application
 * 
 * @author Niwer
 */
public class App {
    public static final Container LOGGER = new Container("Croissant-Flow");
    public static final File BASE_FOLDER = new File("./croissant_flow_data");
    public static final DataBase DATA_BASE = new DataBase(new File(BASE_FOLDER, "main.db"));

    private static Configuration config;

    public static void main(String[] args) {
        LumenEngine.disablePrintingFromDefaultContainer(); // Prevent printing to the default container, we will handle it ourselves
        Console.log("Starting the server").type(CroissantFlowLogTypes.WEB_SERVER).container(LOGGER).send();

        /* Change debug level */
        {
            final Logger JAVALIN_LOGGER = (Logger) LoggerFactory.getLogger("io.javalin");
            JAVALIN_LOGGER.setLevel(Level.WARN);
    
            final Logger JETTY_LOGGER = (Logger) LoggerFactory.getLogger("org.eclipse.jetty");
            JETTY_LOGGER.setLevel(Level.WARN);
        }

        /* Init base folder */
        if(!BASE_FOLDER.exists()) {
            Console.log("Creating base folder at " + BASE_FOLDER.getAbsolutePath()).type(CroissantFlowLogTypes.WEB_SERVER).container(LOGGER).send();
            if(!BASE_FOLDER.mkdirs()) throw new RuntimeException("Failed to create base folder at " + BASE_FOLDER.getAbsolutePath());
        }

        /* Database */
        DATA_BASE.registerTable(TableProduct.class)
            .registerTable(TablePickupSlot.class)
            .registerTable(TableCustomerOrder.class)
            .registerTable(TableOrderItem.class)
            .registerTable(TableAnalyticsMetric.class)
            .registerTable(TableUser.class);

        /* Add the default admin user */
        if(!TableUser.doesUserExist(config().getDefaultAdminEmail())) TableUser.addUser(config().getDefaultAdminEmail(), config().getDefaultAdminPassword(), true);

        /* Initialize the web server */
        {
            final var APP = Javalin.create(cfg -> {
                Console.log("Starting Web Server via Javalin").type(CroissantFlowLogTypes.WEB_SERVER).container(LOGGER).send();
    
                // cfg.defaultContentType = "application/json";
                // cfg.enableCorsForAllOrigins();

                cfg.routes.exception(IllegalArgumentException.class, (e, ctx) -> ctx.status(400).result(e.getMessage()));
                cfg.routes.exception(NumberFormatException.class, (e, ctx) -> ctx.status(400).result("Invalid numeric value"));
                cfg.routes.exception(QueryonException.class, (e, ctx) -> {
                    Console.log("Database query error", e).type(CroissantFlowLogTypes.WEB_SERVER).error().container(LOGGER).send();
                    ctx.status(500).result("Database query error");
                });

                cfg.staticFiles.add("/public");

                IEndpoint.register(cfg, GetProducts.class);
                IEndpoint.register(cfg, PostProducts.class);
                IEndpoint.register(cfg, PutProductDetails.class);
                IEndpoint.register(cfg, PutProductStock.class);
                IEndpoint.register(cfg, DeleteProduct.class);

                IEndpoint.register(cfg, GetPickupSlots.class);
                IEndpoint.register(cfg, PostPickupSlots.class);
                IEndpoint.register(cfg, PutPickupSlotCapacity.class);
                IEndpoint.register(cfg, PutPickupSlotStatus.class);
                IEndpoint.register(cfg, DeletePickupSlot.class);
                
                IEndpoint.register(cfg, GetOrders.class);
                IEndpoint.register(cfg, GetOrderItems.class);
                IEndpoint.register(cfg, PostOrders.class);
                IEndpoint.register(cfg, PutOrderStatus.class);
                IEndpoint.register(cfg, DeleteOrder.class);

                IEndpoint.register(cfg, PostAuthSignUp.class);
                IEndpoint.register(cfg, PostAuthSignIn.class);
            });


            APP.start(config().getServerPort());
        }
        
        /* Add shutdown hooks */
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            Console.log("Shutting down the server").type(CroissantFlowLogTypes.WEB_SERVER).container(LOGGER).send();
            DATA_BASE.disconnect();
        }));
    }

    /**
     * Gets the server configuration, loading it from the config file if it hasn't been loaded yet.
     * 
     * @return The server configuration, loaded from the config file if not already loaded
     */
    public static Configuration config() {
        if (config == null) config = Configuration.fromFile();
        return config;
    }

    /**
     * Hashes a password using SHA-256.
     * 
     * @param password The password to hash
     * @return The hashed password, or an empty string if hashing failed
     */
    public static String hashPassword(String password) {
		try {
			final MessageDigest DIGEST = MessageDigest.getInstance("SHA-256");
			final byte[] BYTES = DIGEST.digest(password.getBytes());

            /* Hash every byte */
			final StringBuilder HASH = new StringBuilder(new BigInteger(1, BYTES).toString(16));
			while (HASH.length() < 32) HASH.insert(0, '0');

			return HASH.toString();
        } catch (NoSuchAlgorithmException e) { return ""; } 
    }

    /**
     * Validates that a string value is not null, empty, or only whitespace. If the value is valid, it is returned trimmed. If the value is invalid, an IllegalArgumentException is thrown with a message indicating which value is invalid.
     * 
     * @param value The string value to validate
     * @param label A label to include in the exception message if the value is invalid (e.g., "Email", "Password", etc.)
     * @return The trimmed value if it is valid
     */
    public static String requireNonBlank(String value, String label) {
        if (value == null) throw new IllegalArgumentException(label + " cannot be null");
        final String normalizedValue = value.trim();
        if (normalizedValue.isEmpty()) throw new IllegalArgumentException(label + " cannot be empty");
        return normalizedValue;
    }
}
