/*
 * This source file was generated by the Gradle 'init' task
 */
package server;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Paths;

import org.junit.jupiter.api.Test;

class ConfigurationTest {
    @Test void configurationHasDefaultServerPort() {
        final Configuration CONFIG = new Configuration();

        assertEquals(7000, CONFIG.getServerPort());
    }

    @Test void configurationCanBeSerializedToJson() {
        final Configuration CONFIG = new Configuration();
        final String JSON = CONFIG.toJson();

        assertNotNull(JSON);
        assertTrue(JSON.contains("server_port"));
    }

    @Test void configurationCanBeDeserializedFromJson() {
        final String JSON = "{ \"server_port\": 8080 }";
        final Configuration CONFIG = Configuration.fromJson(JSON);

        assertNotNull(CONFIG);
        assertEquals(8080, CONFIG.getServerPort());
    }

    @Test void configurationCanBeWrittenToFile() {
        final Configuration CONFIG = new Configuration();
        CONFIG.toFile();

        assertTrue(Files.exists(Paths.get("./config.json")));
    }

    @Test void configurationCanBeReadFromFile() {
        final Configuration CONFIG = new Configuration();
        CONFIG.toFile();

        final Configuration CONFIG_FROM_FILE = Configuration.fromFile();

        assertNotNull(CONFIG_FROM_FILE);
        assertEquals(CONFIG.getServerPort(), CONFIG_FROM_FILE.getServerPort());
    }

    @Test void configurationFromFileReturnsDefaultConfigurationIfFileDoesNotExist() {
        final Configuration CONFIG = Configuration.fromFile();

        assertNotNull(CONFIG);
        assertEquals(7000, CONFIG.getServerPort());
    }
}
